#######################################################################
# This file is a part of SkyPlot
#
# SkyPlot
# Copyright (C) 2026  Shamik Ghosh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# For more information about SkyPlot please visit 
# <https://github.com/1cosmologist/skyplot> or contact Shamik Ghosh 
# at shamik@lbl.gov
#
#########################################################################
[build-system]
requires = ["meson-python>=0.16", "meson>=1.3"]
build-backend = "mesonpy"

[project]
name = "skyplot"
dynamic = ["version"]
description = "Unified CMB sky visualization library for HEALPix and Pixell map."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GPL-3.0-only" }
authors = [
  { name = "Shamik Ghosh" }
]
keywords = ["astronomy", "cmb", "healpix", "healpy", "cartopy", "matplotlib", "visualization"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
  "numpy>=1.24",
  "healpy>=1.16",
  "astropy>=5.0",
  "matplotlib>=3.8",
  "cartopy>=0.23",
  "colormaps>=0.4"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.2",
  "ruff>=0.6"
]
docs = [
  "sphinx>=8.0",
  "shibuya>=2025.7.26",
  "myst-parser>=3.0"
]

[project.urls]
Homepage = "https://github.com/your-org/skyplot"
Documentation = "https://skyplot.readthedocs.io"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
