#######################################################################
# This file is a part of SkyPlot
#
# SkyPlot
# Copyright (C) 2026  Shamik Ghosh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# For more information about SkyPlot please visit 
# <https://github.com/1cosmologist/skyplot> or contact Shamik Ghosh 
# at shamik@lbl.gov
#
#########################################################################

py.install_sources(
  [
    '__init__.py',
    'fonts.py',
    'plotlib.py',
    'plotting.py',
    'sampling.py',
    'saving.py',
  ],
  pure: true,
  subdir: 'skyplot',
)

py.install_sources(
  [
    'fonts/README.md',
    'fonts/texgyreheros-bold.otf',
    'fonts/texgyreheros-bolditalic.otf',
    'fonts/texgyreheros-italic.otf',
    'fonts/texgyreheros-regular.otf',
    'fonts/texgyreheroscn-bold.otf',
    'fonts/texgyreheroscn-bolditalic.otf',
    'fonts/texgyreheroscn-italic.otf',
    'fonts/texgyreheroscn-regular.otf',
  ],
  pure: true,
  subdir: 'skyplot/fonts',
)

py.install_sources(
  [
    'data/planck.dat',
    'data/planck_log.dat',
  ],
  pure: true,
  subdir: 'skyplot/data',
)
